// ──────────────────────────────────────────────
// RIMADLE — Lista de palabras compartida
// Edita este archivo para añadir o quitar palabras
// de cualquier modo sin tocar el código del juego
// ──────────────────────────────────────────────

const WORD_LISTS = {

    // 3 a 5 letras — palabras muy comunes y sencillas
    facil: [
        "SOL","PAN","MAR","PIE","OJO","RED","SAL","PAZ","LUZ","PEZ",
        "DON","RIO","GAS","BOL","ROL","GOL","COL","FAZ","MOL","POL",
        "GATO","CASA","LUNA","MESA","TREN","FLOR","AMOR","PELO","BESO",
        "NUBE","PATO","VINO","ROCA","LAGO","PINO","HOJA","LOBO","RANA",
        "TAZA","BOLA","PIEL","RISA","CAMA","SOPA","PENA","VENA","CENA",
        "CARO","RARO","PESO","ROSA","AZUL","MANO","TORO","LOMO","QUESO",
        "NOCHE","CAMPO","CIELO","FUEGO","VERDE","PLAYA","MONTE","CARTA",
        "LECHE","LIBRO","SILLA","TARDE","MADRE","PADRE","CALLE","VALLE",
        "TORRE","BRISA","PRISA","BARCO","MARCO","CALMA","PALMA","SALSA",
        "MANGA","PASTA","COSTA","PERRO","CERRO","TARRO","BARRO","CARRO",
        "GORRO","MORRO","MIEDO","VIEJO","DUELO","HIELO","SUELO","VUELO",
    ],

    // 6 a 8 letras — palabras conocidas por adultos
    medio: [
        "TRUENO","ESPEJO","CAMINO","SOMBRA","BOSQUE","VUELO","PIEDRA",
        "TIERRA","VIENTO","LLUVIA","FUENTE","MUELLE","PALOMA","CORONA",
        "ESPUMA","CUMBRE","SANGRE","HAMBRE","NOMBRE","GUERRA","FUERZA",
        "PUERTA","VUELTA","BRONCE","ENCAJE","ENLACE","DULCES","FULGOR",
        "NUBLADO","PALMERA","CASCADA","CRISTAL","VENTANA","MOMENTO",
        "TORMENTA","VERANO","PUENTE","CIENCIA","ESPADA","LLANTO","ENCANTO",
        "ARROYO","COLINA","AURORA","MIRADA","SONRISA","ALEGRIA","SOLEDAD",
        "LIBERTAD","CIUDAD","VERDAD","CALOR","TEMBLOR","FERVOR","CLAMOR",
        "SILBIDO","RUGIDO","LATIDO","PARTIDO","VESTIDO","PEDIDO","DESTINO",
        "ESTRELLA","CANCION","CORAZON","PALABRA","TRISTEZA","FANTASIA",
        "ARMONIA","MELODIA","CARACOL","PARASOL","GIRASOL","ARREBOL",
    ],

    // 9 a 11 letras — palabras cultas o poco comunes
    dificil: [
        "CREPUSCULO","MELANCOLIA","LABERINTO","ESPLENDIDO","NOSTALGICO",
        "ABOMINABLE","TREPIDANTE","QUIMERICO","RESONANCIA","TURBULENCIA",
        "FULMINANTE","RESPLANDOR","CAVERNOSO","PORTENTOSO","ARMONIOSO",
        "CLAROSCURO","DESOLACION","PENUMBRA","TEMPESTAD","VENDAVAL",
        "CENTELLA","EVANESCENTE","EFERVESCENTE","PERPLEJIDAD","EXUBERANTE",
        "IMPETUOSO","FULGURANTE","APOCALIPSIS","CATACLISMO","CATASTROFE",
        "ELEGANCIA","ARROGANCIA","IGNORANCIA","TOLERANCIA","OBEDIENCIA",
        "SENSACIONAL","EXCEPCIONAL","EMOCIONAL","RACIONAL","VOCACIONAL",
        "PROFESIONAL","PERSONAL","UNIVERSAL","TEMPORAL","ESPACIAL",
        "TORRENCIAL","EXISTENCIAL","REFERENCIAL","DIFERENCIAL","ESENCIAL",
        "EXPULSADO","RECHAZADO","MARGINADO","OLVIDADO","REPUDIADO",
        "EXILIADO","DESTERRADO","CONDENADO","EJECUTADO","SEPULTADO",
    ],

    // 12 a 16 letras — palabras técnicas, filosóficas o arcaicas
    imposible: [
        "PROCRASTINACION","CONDESCENDIENTE","INCOMPRENSIBLE","EXTRAORDINARIO",
        "MAGNANIMIDAD","EXCOMUNICACION","TRANSCENDENTAL","BIOLUMINISCENCIA",
        "CIRCUNNAVEGAR","METAMORFOSIS","CIRCUNSTANCIAL","CONTRAPRODUCENTE",
        "IMPRESCINDIBLE","IRRESPONSABILIDAD","INCOMPATIBILIDAD","SUSCEPTIBILIDAD",
        "OMNIPRESENTE","PREPONDERANCIA","MAGNIFICENCIA","DESESTABILIZADOR",
        "INCONTESTABLEMENTE","INDISCRIMINADAMENTE","INCONVENIENTEMENTE",
        "IRREMEDIABLEMENTE","IRRESPONSABLEMENTE","IRREVERSIBLEMENTE",
        "DESAFORTUNADAMENTE","DESPROPORCIONADAMENTE","SUPERFICIALIDAD",
        "ESPIRITUALIDAD","SENSACIONALISMO","PROFESIONALISMO","MATERIALISMO",
        "EXISTENCIALISMO","FUNDAMENTALISMO","TOTALITARISMO","AUTORITARISMO",
        "OMNIPOTENCIA","OMNISCIENCIA","TRANSPARENCIA","CONSECUENCIA",
        "INDEPENDENCIA","INTERDEPENDENCIA","CORRESPONDENCIA","INCOHERENCIA",
    ]
};
