// ──────────────────────────────────────────────
// RIMADLE — Lista de palabras compartida
// Edita este archivo para añadir o quitar palabras
// de cualquier modo sin tocar el código del juego
// ──────────────────────────────────────────────

const WORD_LISTS = {

    // 3 a 5 letras — palabras muy comunes y sencillas
    facil: [
        // 3 letras
        "SOL","PAN","MAR","PIE","OJO","RED","SAL","PAZ","LUZ","PEZ",
        "DON","RIO","GAS","BOL","ROL","GOL","COL","FAZ","MOL","POL",
        "SED","FIN","TOS","PUS","RUS","GEL","CID","RON","GIN","TÉ",
        "FEO","REO","CEO","VEO","LEO","NEO","FEA","REA","CEA","SEA",
        "BIS","MIS","TIS","DIS","VIS","HIS","GIS","PIS","RIS","LIS",
        // 4 letras
        "GATO","CASA","LUNA","MESA","TREN","FLOR","AMOR","PELO","BESO",
        "NUBE","PATO","VINO","ROCA","LAGO","PINO","HOJA","LOBO","RANA",
        "TAZA","BOLA","PIEL","RISA","CAMA","SOPA","PENA","VENA","CENA",
        "CARO","RARO","PESO","ROSA","AZUL","MANO","TORO","LOMO","QUESO",
        "PELO","CIELO","VUELO","SUELO","HIELO","DUELO","MIEDO","VIEJO",
        "BESO","HUESO","SESO","PRESO","FRESO","RESO","CESO","MESO",
        "GATO","PATO","RATO","PLATO","TRATO","DATO","HATO","MALO","PALO",
        "MALO","PALO","FALO","HALO","CALO","VALO","RALO","BALO","TALO",
        "COSA","ROSA","POSA","FOSA","BOSA","LOSA","TOSA","DOSA","VOSA",
        "DEDO","CEDO","VEDO","REDO","FEDO","MEDO","LEDO","BEDO","HEDO",
        // 5 letras
        "NOCHE","CAMPO","CIELO","FUEGO","VERDE","PLAYA","MONTE","CARTA",
        "LECHE","LIBRO","SILLA","TARDE","MADRE","PADRE","CALLE","VALLE",
        "TORRE","BRISA","PRISA","BARCO","MARCO","CALMA","PALMA","SALSA",
        "MANGA","PASTA","COSTA","PERRO","CERRO","TARRO","BARRO","CARRO",
        "GORRO","MORRO","BURRO","TURRO","CHURRO","FONDO","MONDO","RONDO",
        "CANTO","LLANTO","MANTO","TANTO","SANTO","BANDO","MANDO","PANDO",
        "TIERRA","GUERRA","SIERRA","PERRA","BELLA","SELLA","HUELLA","MELLA",
        "TALLA","FALLA","MALLA","CALLA","VALLA","BALLA","HALLA","RALLA",
        "NIÑO","MIÑO","PIÑO","RIÑO","SIÑO","TIÑO","VIÑO","LIÑO","FIÑO",
        "NIÑA","PIÑA","RIÑA","TIÑA","VIÑA","LIÑA","FIÑA","MIÑA","SIÑA",
    ],

    // 6 a 8 letras — palabras conocidas por adultos
    medio: [
        // 6 letras
        "TRUENO","ESPEJO","CAMINO","SOMBRA","BOSQUE","PIEDRA","TIERRA",
        "VIENTO","LLUVIA","FUENTE","MUELLE","PALOMA","CORONA","ESPUMA",
        "CUMBRE","SANGRE","HAMBRE","NOMBRE","GUERRA","FUERZA","PUERTA",
        "BRONCE","ENLACE","ENCAJE","FULGOR","TURBIA","HERIDA","SALIDA",
        "NEVADA","LLEGADA","MIRADA","PARADA","TIRADA","JUGADA","PASADA",
        "TOCADO","HELADO","PARADO","TIRADO","PESADO","CANSADO","PINTADO",
        "BONITO","FINITO","SOLITO","QUIETO","PRIETO","NIETO","NETO",
        "MOLINO","CAMINO","DESTINO","PEPINO","CASINO","VECINO","MARINO",
        "CANTAR","BAILAR","VIAJAR","GRITAR","LLORAR","RONDAR","TREPAR",
        "CANTOR","PASTOR","DOCTOR","RECTOR","SECTOR","VECTOR","FACTOR",
        "ESPADA","PARADA","ENTRADA","MIRADA","NEVADA","LLEGADA","CRUZADA",
        "FAMOSA","HERMOSA","PRECIOSA","GOLOSA","DUDOSA","NERVIOSA","COSTOSA",
        // 7 letras
        "NUBLADO","PALMERA","CASCADA","CRISTAL","VENTANA","MOMENTO","VERANO",
        "ENCANTO","ARROYO","COLINA","AURORA","SONRISA","ALEGRIA","SOLEDAD",
        "CALIDAD","LEALTAD","BONDAD","CIUDAD","VERDAD","MALDAD","CRUELDAD",
        "SILBIDO","RUGIDO","LATIDO","PARTIDO","VESTIDO","PEDIDO","DESTINO",
        "PELIGRO","ABRIGO","AMIGO","TESTIGO","CASTIGO","PRODIGO","PRODIGO",
        "SERPIENTE","VALIENTE","PACIENTE","CLIENTE","ORIENTE","PONIENTE",
        "CARRERA","MADERA","BANDERA","ESCALERA","CADERA","HIGUERA","ESPERA",
        "MAÑANA","VENTANA","CAMPANA","SULTANA","MARIANA","INDIANA","CUBANA",
        "CAMINAR","TRABAJAR","REGRESAR","SOÑAR","CANTAR","VOLAR","LLEGAR",
        "CALOR","DOLOR","AMOR","RUMOR","VALOR","TEMBLOR","FERVOR","CLAMOR",
        // 8 letras
        "SILENCIO","ESTRELLA","CANCION","CORAZON","PALABRA","TRISTEZA",
        "FANTASIA","ARMONIA","MELODIA","CARACOL","PARASOL","GIRASOL",
        "LIBERTAD","AVENTURA","TERNURA","DULZURA","FRESCURA","LOCURA",
        "HERMANOS","ANCIANOS","VILLANOS","ENANOS","PLANOS","LLANOS","SANOS",
        "JARDINES","COLINES","MARINES","COFINES","BOTINES","PATINES","FESTINES",
        "GLORIOSO","FAMOSO","HERMOSO","PRECIOSO","RUIDOSO","DICHOSO","FURIOSO",
        "NACIONES","CANCIONES","PASIONES","RAZONES","VISIONES","MISIONES",
        "PALACIO","ESPACIO","SERVICIO","PRECIPICIO","EDIFICIO","OFICIO",
    ],

    // 9 a 11 letras — palabras cultas o poco comunes
    dificil: [
        // 9 letras
        "LABERINTO","QUIMERICO","CAVERNOSO","PORTENTOSO","ARMONIOSO",
        "TEMPESTAD","VENDAVAL","CENTELLA","PENUMBRA","EXUBERANTE",
        "IMPETUOSO","CATASTROFE","ELEGANCIA","ARROGANCIA","IGNORANCIA",
        "TOLERANCIA","OBEDIENCIA","EXISTENCIA","RESISTENCIA","INSISTENCIA",
        "PERSEVERA","ESPERANZA","CONFIANZA","VIGILANCIA","DISTANCIA",
        "PACIENCIA","VIOLENCIA","INOCENCIA","DECADENCIA","TENDENCIA",
        "MAJESTUOSO","TORMENTOSO","MISTERIOSO","MELODIOSO","CAPRICHOSO",
        "PELIGROSO","ASOMBROSO","ESPLENDIDO","MISERABLE","ADMIRABLE",
        "INVENCIBLE","INCREIBLE","INFALIBLE","INVISIBLE","INFLEXIBLE",
        "TREMENDO","ESTUPENDO","HORRORENDO","NEFASTO","FUNESTO","MOLESTO",
        // 10 letras
        "CREPUSCULO","MELANCOLIA","NOSTALGICO","ABOMINABLE","TREPIDANTE",
        "RESONANCIA","TURBULENCIA","FULMINANTE","RESPLANDOR","CLAROSCURO",
        "DESOLACION","PERPLEJIDAD","FULGURANTE","APOCALIPSIS","CATACLISMO",
        "SENSACIONAL","EXCEPCIONAL","EMOCIONAL","VOCACIONAL","PROFESIONAL",
        "EXISTENCIAL","REFERENCIAL","DIFERENCIAL","TORRENCIAL","CEREMONIAL",
        "CONMOVEDORA","SORPRENDENTE","IMPONENTE","RELUCIENTE","ARDIENTE",
        "PREPOTENCIA","PROVIDENCIA","MAGNIFICENCIA","OMNIPOTENCIA","CLEMENCIA",
        "CONSECUENCIA","TRANSPARENCIA","INDEPENDENCIA","INCOHERENCIA",
        "EXCELENCIA","BENEVOLENCIA","EQUIVALENCIA","MAGNIFICENCIA","DECADENCIA",
        "IMAGINACION","ADMIRACION","INSPIRACION","GENERACION","LIBERACION",
        // 11 letras
        "EVANESCENTE","EFERVESCENTE","VERTIGINOSO","PORTENTOSIDAD","TREPIDACION",
        "REMINISCENCIA","OMNISCIENCIA","CONSECUENCIA","CORRESPONDENCIA",
        "CONTRADICCION","INSATISFECHO","INCONSOLABLE","IMPERECEDERO",
        "DESCONSOLADO","DESLUMBRANTE","GRANDIOSIDAD","MAGNIFICENCIA",
        "ESPLENDIDEZ","GENEROSIDAD","CURIOSIDAD","CREATIVIDAD","SENSIBILIDAD",
        "INESTABILIDAD","IRREGULARIDAD","IRRACIONALIDAD","INFORMALIDAD",
        "ORIGINALIDAD","BRUTALIDAD","MORALIDAD","MENTALIDAD","VITALIDAD",
        // más difícil
        "MELANCÓLICO","FANTÁSTICO","MAGNÉTICO","SIMPÁTICO","DRAMÁTICO",
        "ENIGMÁTICO","LUNÁTICO","PIRÁTICO","TEMÁTICO","ACUÁTICO",
        "TRAUMÁTICO","PRAGMÁTICO","DOGMÁTICO","ESQUEMÁTICO","SISTEMÁTICO",
        "CATASTROF","CATARTICO","HIPNOTICO","EXOTICO","NARCÓTICO","FANATICO",
        "SARCASMO","ENTUSIASMO","ESPASMO","ORGASMO","ABISMO","CINISMO",
        "ESCEPTICISMO","OPTIMISMO","PESIMISMO","EGOÍSMO","HEROISMO",
        "FERVOROSO","DICHOSO","FURIOSO","LLOROSO","GENEROSO","PIADOSO",
        "AMBICIOSO","CAPRICHOSO","ESCANDALOSO","FASTIDIOSO","HORROROSO",
        "MONSTRUOSO","NEBULOSO","ONDULOSO","PEDREGOSO","RELIGIOSO",
        "VENENOSO","ABUNDOSO","CHISTOSO","TEMEROSO","RIGUROSO","LUMINOSO",
        "ESPANTOSO","VIRTUOSO","ORGULLOSO","FABULOSO","GLORIOSO","NEBULOSO",
        "PODEROSO","VALEROSO","MARAVILLOSO","RESPETUOSO","ASOMBROSO",
    ],

    // 12 a 16 letras — palabras técnicas, filosóficas o arcaicas
    imposible: [
        // 12 letras
        "MAGNANIMIDAD","METAMORFOSIS","SUPERSTICION","EXTRAVAGANCIA",
        "OMNIPRESENTE","PREPONDERANCIA","CONTEMPLACION","MAGNIFICENCIA",
        "SUSCEPTIBILIDAD","DISPONIBILIDAD","ACCESIBILIDAD","COMPATIBILIDAD",
        "RESPONSABILIDAD","VULNERABILIDAD","SOSTENIBILIDAD","BIODIVERSIDAD",
        "RADIOACTIVIDAD","HORIZONTALIDAD","VERTICALIDAD","ORIGINALIDAD",
        "IRRACIONALIDAD","INFORMALIDAD","IRREGULARIDAD","INESTABILIDAD",
        "IMPARCIALIDAD","BRUTALIDAD","MORALIDAD","MENTALIDAD","VITALIDAD",
        "OMNIPOTENCIA","TRANSPARENCIA","CONSECUENCIA","INDEPENDENCIA",
        // 13 letras
        "CIRCUNNAVEGAR","EXTRAORDINARIO","INCOMPRENSIBLE","CONDESCENDIENTE",
        "PROCRASTINACION","EXCOMUNICACION","TRANSCENDENTAL","CIRCUNSTANCIAL",
        "CONTRAPRODUCENTE","IRRESPONSABILIDAD","INCOMPATIBILIDAD","SUSCEPTIBILIDAD",
        "PREPONDERANCIA","DESESTABILIZADOR","INTERMINABLEMENTE","PERPETUAMENTE",
        "INCONTESTABLEMENTE","INDISCRIMINADAMENTE","INCONVENIENTEMENTE",
        "IRREMEDIABLEMENTE","IRRESPONSABLEMENTE","IRREVERSIBLEMENTE",
        "DESAFORTUNADAMENTE","DESPROPORCIONADAMENTE","SUPERFICIALIDAD",
        "PROFESIONALISMO","SENSACIONALISMO","EXISTENCIALISMO","FUNDAMENTALISMO",
        // 14-16 letras
        "BIOLUMINISCENCIA","PROCRASTINACION","CONDESCENDIENTE","EXTRAORDINARIO",
        "ANTICONSTITUCIONAL","DESCENTRALIZACION","DEMOCRATIZACION",
        "INDUSTRIALIZACION","PROFESIONALIZACION","INTERNACIONALIZACION",
        "ELECTROMAGNETISMO","TERMODINAMICA","HIDRODINAMICA","FOTOSINTESIS",
        "IRRESPONSABILIDAD","INCOMPATIBILIDAD","SUSCEPTIBILIDAD","VULNERABILIDAD",
        "DESESTABILIZADOR","INTERMINABLEMENTE","PRECIPITADAMENTE","SUBTERRANEA",
        "OMNIPRESENTE","PREPONDERANCIA","MAGNIFICENCIA","REMINISCENCIA",
        "CONDESCENDENCIA","INADMISIBLE","INCONTROVERTIBLE","ELECTROENCEFALOGRAMA",
        "CONTRAMANIFESTACION","ANTIINFLAMATORIO","DESINDUSTRIALIZACION",
        "INCONSTITUCIONAL","DESCLASIFICACION","INTERNACIONALIZACION",
        // más imposible
        "RESPONSABILIDAD","IMPARCIALIDAD","ESPIRITUALIDAD","TERRITORIALIDAD",
        "PUNTUALIDAD","SENSACIONALISMO","MATERIALISMO","TOTALITARISMO",
        "AUTORITARISMO","CAPITALISMO","SOCIALISMO","COMUNISMO","FASCISMO",
        "IMPERIALISMO","COLONIALISMO","ANARQUISMO","SINDICALISMO","LIBERALISMO",
        "CONSERVADURISMO","REPUBLICANISMO","PARLAMENTARISMO","FEDERALISMO",
        "NACIONALISMO","SEPARATISMO","AUTONOMISMO","REGIONALISMO","LOCALISMO",
        "CONSTITUCIONALISMO","INSTITUCIONALISMO","INTERVENCIONISMO","PROTECCIONISMO",
        "MERCANTILISMO","MONETARISMO","KEYNESIANISMO","NEOLIBERALISMO",
        "AMBIENTALISMO","ECOLOGISMO","FEMINISMO","PACIFISMO","HUMANISMO",
        "RELATIVISMO","ABSOLUTISMO","PRAGMATISMO","EMPIRISMO","RACIONALISMO",
        "EXISTENCIALISMO","NIHILISMO","POSITIVISMO","NATURALISMO","IDEALISMO",
        "ESTOICISMO","EPICUREISMO","PLATONISMO","ARISTOTELISMO","KANTISMO",
        "HEGELIANISMO","MARXISMO","FREUDISMO","DARWINISMO","NEWTONIANISMO",
        "INCOMPRENSIBILIDAD","IRRESPONSABILIDADES","CONDESCENDENCIAS",
        "EXTRAORDINARIAMENTE","INCONSTITUCIONALMENTE","DESPROPORCIONALMENTE",
    ]
};
