// ──────────────────────────────────────────────
// RIMADLE — Lista de palabras compartida
// Edita este archivo para añadir o quitar palabras
// de cualquier modo sin tocar el código del juego
// ──────────────────────────────────────────────

const WORD_LISTS = {

    // 3 a 5 letras — palabras muy comunes y sencillas
    facil: [
        // 3 letras
        "SOL","PAN","MAR","PIE","OJO","RED","SAL","PAZ","LUZ","PEZ",
        "DON","RIO","GAS","BOL","ROL","GOL","COL","FAZ","MOL","POL",
        "SED","FIN","TOS","GEL","CID","RON","GIN",
        "FEO","REO","VEO","LEO","NEO","FEA","REA","SEA",
        "BIS","MIS","DIS","VIS","GIS","RIS","LIS",
        // 4 letras
        "GATO","CASA","LUNA","MESA","TREN","FLOR","AMOR","PELO","BESO",
        "NUBE","PATO","VINO","ROCA","LAGO","PINO","HOJA","LOBO","RANA",
        "TAZA","BOLA","PIEL","RISA","CAMA","SOPA","PENA","VENA","CENA",
        "CARO","RARO","PESO","ROSA","AZUL","MANO","TORO","LOMO",
        "CIELO","VUELO","SUELO","HIELO","DUELO","MIEDO","VIEJO",
        "HUESO","SESO","PRESO","RATO","PLATO","TRATO","DATO",
        "MALO","PALO","FALO","HALO","CALO","RALO",
        "COSA","POSA","FOSA","LOSA",
        "DEDO","CEDO","REDO","MEDO","LEDO",
        // 5 letras
        "NOCHE","CAMPO","FUEGO","VERDE","PLAYA","MONTE","CARTA",
        "LECHE","LIBRO","SILLA","TARDE","MADRE","PADRE","CALLE","VALLE",
        "TORRE","BRISA","PRISA","BARCO","MARCO","CALMA","PALMA","SALSA",
        "MANGA","PASTA","COSTA","PERRO","CERRO","TARRO","BARRO","CARRO",
        "GORRO","MORRO","BURRO","CHURRO","FONDO","MONDO",
        "CANTO","LLANTO","MANTO","TANTO","SANTO","BANDO","MANDO",
        "TIERRA","GUERRA","SIERRA","PERRA","BELLA","SELLA","HUELLA","MELLA",
        "TALLA","FALLA","MALLA","CALLA","VALLA","HALLA","RALLA",
        "NIÑO","PIÑO","RIÑO","TIÑO","VIÑO","LIÑO",
        "NIÑA","PIÑA","RIÑA","TIÑA","VIÑA","LIÑA"
    ],

    // 6 a 8 letras — palabras conocidas por adultos
    medio: [
        // 6 letras
        "TRUENO","ESPEJO","CAMINO","SOMBRA","BOSQUE","PIEDRA","TIERRA",
        "VIENTO","LLUVIA","FUENTE","MUELLE","PALOMA","CORONA","ESPUMA",
        "CUMBRE","SANGRE","HAMBRE","NOMBRE","GUERRA","FUERZA","PUERTA",
        "BRONCE","ENLACE","ENCAJE","FULGOR","HERIDA","SALIDA",
        "NEVADA","LLEGADA","MIRADA","PARADA","TIRADA","JUGADA","PASADA",
        "TOCADO","HELADO","PARADO","TIRADO","PESADO","CANSADO","PINTADO",
        "BONITO","FINITO","QUIETO","PRIETO","NIETO",
        "MOLINO","DESTINO","PEPINO","CASINO","VECINO","MARINO",
        "CANTAR","BAILAR","VIAJAR","GRITAR","LLORAR","RONDAR","TREPAR",
        "CANTOR","PASTOR","DOCTOR","RECTOR","SECTOR","VECTOR","FACTOR",
        "ESPADA","ENTRADA","CRUZADA",
        "FAMOSA","HERMOSA","PRECIOSA","GOLOSA","DUDOSA","NERVIOSA","COSTOSA",
        // 7 letras
        "NUBLADO","PALMERA","CASCADA","CRISTAL","VENTANA","MOMENTO","VERANO",
        "ENCANTO","ARROYO","COLINA","AURORA","SONRISA","ALEGRIA","SOLEDAD",
        "CALIDAD","LEALTAD","BONDAD","CIUDAD","VERDAD","MALDAD","CRUELDAD",
        "SILBIDO","RUGIDO","LATIDO","PARTIDO","VESTIDO","PEDIDO",
        "PELIGRO","ABRIGO","AMIGO","TESTIGO","CASTIGO","PRODIGO",
        "VALIENTE","PACIENTE","CLIENTE","ORIENTE","PONIENTE",
        "CARRERA","MADERA","BANDERA","ESCALERA","CADERA","HIGUERA","ESPERA",
        "MAÑANA","CAMPANA","SULTANA","MARIANA","CUBANA",
        "CAMINAR","TRABAJAR","REGRESAR","VOLAR","LLEGAR",
        "CALOR","DOLOR","AMOR","RUMOR","VALOR","TEMBLOR","FERVOR","CLAMOR",
        // 8 letras
        "SILENCIO","ESTRELLA","CANCION","CORAZON","PALABRA","TRISTEZA",
        "FANTASIA","ARMONIA","MELODIA","CARACOL","PARASOL","GIRASOL",
        "LIBERTAD","AVENTURA","TERNURA","DULZURA","FRESCURA","LOCURA",
        "HERMANOS","ANCIANOS","VILLANOS","ENANOS","PLANOS","LLANOS","SANOS",
        "JARDINES","BOTINES","PATINES","FESTINES",
        "GLORIOSO","HERMOSO","PRECIOSO","RUIDOSO","DICHOSO","FURIOSO",
        "NACIONES","CANCIONES","PASIONES","RAZONES","VISIONES","MISIONES",
        "PALACIO","ESPACIO","SERVICIO","EDIFICIO","OFICIO"
    ],

    // 9 a 11 letras — palabras cultas o poco comunes
    dificil: [
        "LABERINTO","QUIMERICO","CAVERNOSO","PORTENTOSO","ARMONIOSO",
        "TEMPESTAD","VENDAVAL","CENTELLA","PENUMBRA","EXUBERANTE",
        "IMPETUOSO","CATASTROFE","ELEGANCIA","ARROGANCIA","IGNORANCIA",
        "TOLERANCIA","OBEDIENCIA","EXISTENCIA","RESISTENCIA","INSISTENCIA",
        "ESPERANZA","CONFIANZA","VIGILANCIA","DISTANCIA",
        "PACIENCIA","VIOLENCIA","INOCENCIA","TENDENCIA",
        "MAJESTUOSO","TORMENTOSO","MISTERIOSO","MELODIOSO","CAPRICHOSO",
        "PELIGROSO","ASOMBROSO","ESPLENDIDO","MISERABLE","ADMIRABLE",
        "INVENCIBLE","INCREIBLE","INFALIBLE","INVISIBLE","INFLEXIBLE",
        "TREMENDO","ESTUPENDO","NEFASTO","FUNESTO","MOLESTO",
        "CREPUSCULO","MELANCOLIA","NOSTALGICO","ABOMINABLE","TREPIDANTE",
        "RESONANCIA","TURBULENCIA","FULMINANTE","RESPLANDOR","CLAROSCURO",
        "DESOLACION","PERPLEJIDAD","FULGURANTE","APOCALIPSIS","CATACLISMO",
        "SENSACIONAL","EXCEPCIONAL","EMOCIONAL","VOCACIONAL","PROFESIONAL",
        "EXISTENCIAL","REFERENCIAL","DIFERENCIAL","TORRENCIAL","CEREMONIAL",
        "CONMOVEDORA","IMPONENTE","RELUCIENTE","ARDIENTE",
        "PREPOTENCIA","PROVIDENCIA","OMNIPOTENCIA","CLEMENCIA",
        "CONSECUENCIA","TRANSPARENCIA","INDEPENDENCIA","INCOHERENCIA",
        "EXCELENCIA","BENEVOLENCIA","EQUIVALENCIA",
        "IMAGINACION","ADMIRACION","INSPIRACION","GENERACION","LIBERACION",
        "EVANESCENTE","EFERVESCENTE","VERTIGINOSO","TREPIDACION",
        "REMINISCENCIA","OMNISCIENCIA","CORRESPONDENCIA",
        "CONTRADICCION","INCONSOLABLE","IMPERECEDERO",
        "DESCONSOLADO","DESLUMBRANTE","GRANDIOSIDAD",
        "GENEROSIDAD","CURIOSIDAD","CREATIVIDAD","SENSIBILIDAD",
        "INESTABILIDAD","IRREGULARIDAD","IRRACIONALIDAD","INFORMALIDAD",
        "ORIGINALIDAD","BRUTALIDAD","MORALIDAD","MENTALIDAD","VITALIDAD",
        "ENIGMATICO","LUNATICO","TEMATICO","ACUATICO",
        "TRAUMATICO","PRAGMATICO","DOGMATICO","ESQUEMATICO","SISTEMATICO",
        "CATARTICO","HIPNOTICO","EXOTICO","NARCOTICO","FANÁTICO",
        "SARCASMO","ENTUSIASMO","ESPASMO","ABISMO","CINISMO",
        "ESCEPTICISMO","OPTIMISMO","PESIMISMO","HEROISMO",
        "FERVOROSO","LLOROSO","GENEROSO","PIADOSO",
        "AMBICIOSO","ESCANDALOSO","FASTIDIOSO","HORROROSO",
        "MONSTRUOSO","NEBULOSO","ONDULOSO","PEDREGOSO","RELIGIOSO",
        "VENENOSO","CHISTOSO","TEMEROSO","RIGUROSO","LUMINOSO",
        "ESPANTOSO","VIRTUOSO","ORGULLOSO","FABULOSO",
        "PODEROSO","VALEROSO","MARAVILLOSO","RESPETUOSO"
    ],

    // 12 a 16 letras — palabras técnicas, filosóficas o arcaicas
    imposible: [
        "MAGNANIMIDAD","METAMORFOSIS","SUPERSTICION","EXTRAVAGANCIA",
        "CONTEMPLACION",
        "DISPONIBILIDAD","ACCESIBILIDAD","COMPATIBILIDAD",
        "VULNERABILIDAD","SOSTENIBILIDAD","BIODIVERSIDAD",
        "RADIOACTIVIDAD","HORIZONTALIDAD","VERTICALIDAD",
        "IMPARCIALIDAD","OMNIPOTENCIA","INDEPENDENCIA",
        "CIRCUNNAVEGAR","EXTRAORDINARIO","INCOMPRENSIBLE","CONDESCENDIENTE",
        "PROCRASTINACION","EXCOMUNICACION","TRANSCENDENTAL","CIRCUNSTANCIAL",
        "CONTRAPRODUCENTE","IRRESPONSABILIDAD","INCOMPATIBILIDAD",
        "INCONTESTABLEMENTE","INDISCRIMINADAMENTE","INCONVENIENTEMENTE",
        "IRREMEDIABLEMENTE","IRRESPONSABLEMENTE","IRREVERSIBLEMENTE",
        "DESAFORTUNADAMENTE","DESPROPORCIONADAMENTE","SUPERFICIALIDAD",
        "PROFESIONALISMO","FUNDAMENTALISMO",
        "BIOLUMINISCENCIA",
        "ANTICONSTITUCIONAL","DESCENTRALIZACION","DEMOCRATIZACION",
        "INDUSTRIALIZACION","PROFESIONALIZACION","INTERNACIONALIZACION",
        "ELECTROMAGNETISMO","TERMODINAMICA","HIDRODINAMICA","FOTOSINTESIS",
        "PRECIPITADAMENTE","SUBTERRANEA","REMINISCENCIA",
        "CONDESCENDENCIA","INADMISIBLE","ELECTROENCEFALOGRAMA",
        "CONTRAMANIFESTACION","ANTIINFLAMATORIO","DESINDUSTRIALIZACION",
        "INCONSTITUCIONAL","DESCLASIFICACION",
        "ESPIRITUALIDAD","TERRITORIALIDAD","PUNTUALIDAD",
        "TOTALITARISMO","AUTORITARISMO","CAPITALISMO","SOCIALISMO",
        "COMUNISMO","FASCISMO","IMPERIALISMO","COLONIALISMO",
        "ANARQUISMO","SINDICALISMO","LIBERALISMO","CONSERVADURISMO",
        "REPUBLICANISMO","PARLAMENTARISMO","FEDERALISMO",
        "NACIONALISMO","SEPARATISMO","AUTONOMISMO","REGIONALISMO",
        "CONSTITUCIONALISMO","INSTITUCIONALISMO","INTERVENCIONISMO","PROTECCIONISMO",
        "MERCANTILISMO","MONETARISMO","KEYNESIANISMO","NEOLIBERALISMO",
        "AMBIENTALISMO","ECOLOGISMO","FEMINISMO","PACIFISMO","HUMANISMO",
        "RELATIVISMO","ABSOLUTISMO","PRAGMATISMO","EMPIRISMO","RACIONALISMO",
        "NIHILISMO","POSITIVISMO","NATURALISMO","IDEALISMO",
        "ESTOICISMO","EPICUREISMO","PLATONISMO","ARISTOTELISMO","KANTISMO",
        "HEGELIANISMO","MARXISMO","FREUDISMO","DARWINISMO","NEWTONIANISMO",
        "INCOMPRENSIBILIDAD","CONDESCENDENCIAS",
        "EXTRAORDINARIAMENTE","INCONSTITUCIONALMENTE","DESPROPORCIONALMENTE"
    ]
};
